name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['OS=16.2,name="iPhone 14 Pro"']

    steps:
    - uses: actions/checkout@v2
    - name: Swift Lint
      run: swiftlint
    - name: delete unpaired watch sims
      run: |
        xcrun simctl list --json > simulators.json
        watch_os_udids=$(jq '.devices[] | map(select(.name | contains("Watch"))) | .[].udid' simulators.json -r)
        paired_watch_udids=$(jq '.pairs | map(.watch) | .[].udid' simulators.json -r)

        while IFS= read -r udid; do
          if [[ ! "${paired_watch_udids[*]}" =~ "${udid}" ]]; then
            xcrun simctl delete ${udid}
          fi
        done <<< "$watch_os_udids"
    - name: Run Test
      working-directory: MixpanelDemo
      run: |
        set -o pipefail
        xcodebuild -scheme MixpanelDemo -derivedDataPath Build/ -destination ${{ matrix.destination }} -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES -enableCodeCoverage YES clean build test | xcpretty -c;
    - name: Pod Lint
      run: pod lib lint --allow-warnings --verbose
    - name: Code Coverage Report
      working-directory: MixpanelDemo/build/Logs/Test
      run: |
        xcrun xccov view --report --files-for-target Mixpanel.framework  *.xcresult
        xcrun xccov view --report --only-targets *.xcresult
